name: Setup
description: Set up CI toolchain
runs:
  using: composite
  steps:
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          ~/.cargo/env
          ~/.rustup
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - uses: jdx/mise-action@v3
      with:
        experimental: true
        log_level: debug

    - name: Install and toolchain
      shell: bash
      run: |
        # Ensure Rust toolchain is properly installed before running tests
        mise install rust
        # Install required components explicitly
        mise exec rust -- rustup component add rustfmt clippy
